module.exports = {
    '0'     : 'Status Ok',
    '1'     : 'User not authenticated.',
    '2'     : 'User not found.',
    '3'     : 'Authorization error, check your username and password.',
    '4'     : 'Users not found.',
    '10'    : 'Validation form errors.',
    '20'    : 'User with email already exists.',
    '21'    : 'Password does not coincide with confirm.',
    '22'    : 'The password is the same as the old one.',
    '23'    : 'Update user error.',
    '30'    : 'Token not generated.',
    '31'    : 'Token not found.',
    '32'    : 'Token expired!',
    '33'    : 'You are not the owner this service.',
    '34'    : 'Service not found.',
    '35'    : 'Order not found.',
    '36'    : 'Order-Photo not found.',
    '37'    : 'Photo not found.',
    '38'    : 'Paper not found.',
    '39'    : 'Type not found.',
    '40'    : 'Size not found.',
    '41'    : 'Price not found.',
    '50'    : 'No database connection',
    '60'    : 'Has no files on your request',
    '100'   : 'Unknown error!',
    '404'   : 'Unknown Endpoint or method.',
    '500'   : 'The server cannot process your request.'
}